### ISSUE TITLE
Documentation clarification: "compiled with a modified wasm2c compiler"

### ISSUE THREAD

**Issue by squk** [PLSysSec/rlbox_wasm2c_sandbox#11]
The documentation states 
> Integration with RLBox sandboxing API to leverage the sandboxing in WASM modules compiled with a modified wasm2c compiler.

However in the `CMakeLists.txt` it appears [`wabt` is downloaded without any local modification](https://github.com/PLSysSec/rlbox_wasm2c_sandbox/blob/master/CMakeLists.txt#L122-L125). 

Is it correct to say that [rlbox_wasm2c_sandbox](https://github.com/PLSysSec/rlbox_wasm2c_sandbox) does not currently depend on a modified wasm2c compiler? Are there plans to make modifications to the compiler?

**Comment by shravanrn** [comment]
Thanks for pointing this out. We moved to using the upstream wabt repo a while back, and it looks like we've missed updating the documentation in some places. Will fix.

> Are there plans to make modifications to the compiler?

Most of the modifications we have made to support library sandboxing have already been upstreamed, so our plan is to continue using the upstream wabt.
