### ISSUE TITLE
Support using wasm2c modules built with exported memories

### ISSUE THREAD

**Issue by squk** [PLSysSec/rlbox_wasm2c_sandbox#12]
It would be nice if `rlbox_wasm2c_sandbox` supported sandboxing with wasm2c modules that have been built with one or more of the exported memory compile options(i.e. `--export-table` and `--export-memory`). 

Thread for context : https://github.com/emscripten-core/emscripten/commit/06825ec9e4bbee3ecb6c13111146d61bdc0a522b#r138497857

**Comment by shravanrn** [comment]
acknowledged. Investigating how to support this!

**Comment by shravanrn** [comment]
Done in #13
