### ISSUE TITLE
Do you have any benchmark?

### ISSUE THREAD

**Issue by tkyzp** [PLSysSec/rlbox_wasm2c_sandbox#8]
Do you have any benchmark? And how can I get the benchmark src?

**Comment by shravanrn** [comment]
Hi, 
Sorry for the delay in responding, I was traveling these last few days. One of the standalone benchmarks we use as a quick performance guide is a JPEG re-coding test. I need to clean this up and setup some infrastructure for this, but the code is test is essentially a single file here

https://github.com/shravanrn/libjpeg-turbo_nacltests/blob/wasm_test/example_wasm.cpp

You can compile this file along with libjpeg into a wasm module and check the time taken to re-code.

The performance tests we use other than this are a part of the Firefox browser. For instance we check the performance of sandboxing libgraphite with wasm by measuring the performance of loading this test page which contains graphite fonts (https://jfkthame.github.io/test/udhr_urd.html)

Feel free to close the bug if the above is sufficient info or let me know if you need more information
